### ISSUE TITLE
使用`@hamster-bot/constructeur`代替原有的`tsconfig.json`

### ISSUE THREAD

**Issue by SaarChaffee** [AwesomeHamster/ffxiv-cn-news-reptile#6]

**Comment by MaikoTan** [comment]
`@hamster-bot/constructeur` 主要用处在于构建 `koishi` 插件，用于这个与 koishi 无关的软件包可能不太好。
因此这个 issue 与相关的 PR 暂且保留，等待之后讨论。

**Comment by MaikoTan** [comment]
As described above, the `@hamster-bot/constructeur` package is not intended to build non-koishi-plugins, so this issue would be closed as not planned.
